name: apple_music
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  image_picker: ^0.8.7+4
  cupertino_icons: ^1.0.2
  get: 4.6.6
  http: ^0.13.5
  webview_flutter: ^3.0.4
  #get storage package
  get_storage: ^2.1.1
  file_picker: ^8.0.0+1
  # video player package
  video_player: ^2.9.1
  just_audio: ^0.9.2
  audio_service: ^0.18.0
  speech_to_text: ^6.6.0
  permission_handler: ^11.3.1
  flutter: 
    sdk: flutter
  firebase_core: ^2.15.1
  cloud_firestore: ^4.15.8
  intl: ^0.18.1
  firebase_auth: ^4.7.3
  firebase_messaging: ^14.6.6
  flutter_local_notifications: ^15.1.0+1
  shared_preferences: ^2.2.0
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.5.2
  url_launcher:  ^6.2.0
  connectivity_plus: ^6.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - lib/app/assets/

